### PR TITLE
Added method call to intialize MoEngage SDK with senderId and appId. …

### PR DESCRIPTION
**Pull request by prashant74**
Added method call to intialize MoEngage SDK with senderId and appId. …Changed MoEngage SDK version to 5.3.24 in gradle

### CODE REVIEW

**Comment by moeNandi** [comment]
@f2prateek can you get this merged

**Comment by f2prateek** [comment]
CI is failing.

**Comment by moeNandi** [comment]
@f2prateek the 1st was a checStyle issue, th next was a mocking issue and the final was all well. Even then if it fails, can you please provide the logs because, circleci says everything is fine

**Comment by f2prateek** [comment]
Ah I didn't see the follow up commits. Please squash them into one and looks good to go.

**Comment by moeNandi** [comment]
@f2prateek can you please get this merged now ?

**Comment by f2prateek** [comment]
@moeNandi you didn't add any tests for this. You need to add a verification that the heper initialize method was called with right arguments. Let me know when that is done and we can release this.

**Comment by prashant74** [comment]
@f2prateek I have added the verification for initialize method getting called with right arguments.Please have a look.

**Comment by f2prateek** [comment]
Thanks!

**Pull request merged**
